openapi: 3.0.3
info:
  version: 2023.1.1
  title: Lambda Lecture Sample API
  description: This is a sample API for Lambda Lecture.
servers:
- url: https://xxx.xxx
  description: API Gateway
tags:
- name: Order
  description: 注文リソースに対する操作
paths:
  /order:
    $ref: ./paths/order.yaml#/order
security:
- CognitoAuthotizer: []
